# Generated by Django 5.2.7 on 2025-10-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_remove_order_created_by_alter_order_status_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
