# Generated by Django 5.2.7 on 2025-10-23 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('intent_id', models.CharField()),
                ('client_secret', models.CharField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intent', to='pos.order')),
            ],
        ),
    ]
