# Generated by Django 5.2.7 on 2025-10-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_paymentintent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
