# Generated by Django 5.2.7 on 2025-10-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='client_secret',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='intent_id',
            field=models.CharField(unique=True),
        ),
    ]
